
//input ports
add mapped point CLK CLK -type PI PI
add mapped point RSTn RSTn -type PI PI

//output ports
add mapped point LED_HEART LED_HEART -type PO PO
add mapped point LED_PACE LED_PACE -type PO PO

//inout ports




//Sequential Pins
add mapped point lif_inst/spike_out/q lif_inst/spike_out_reg/Q  -type DFF DFF
add mapped point lif_inst/refract_cnt[1]/q lif_inst/refract_cnt_reg[1]/Q  -type DFF DFF
add mapped point lif_inst/refract_cnt[0]/q lif_inst/refract_cnt_reg[0]/Q  -type DFF DFF
add mapped point lif_inst/v[10]/q lif_inst/v_reg[10]/Q  -type DFF DFF
add mapped point lif_inst/v[11]/q lif_inst/v_reg[11]/Q  -type DFF DFF
add mapped point lif_inst/v[12]/q lif_inst/v_reg[12]/Q  -type DFF DFF
add mapped point lif_inst/v[13]/q lif_inst/v_reg[13]/Q  -type DFF DFF
add mapped point lif_inst/v[14]/q lif_inst/v_reg[14]/Q  -type DFF DFF
add mapped point lif_inst/v[15]/q lif_inst/v_reg[15]/Q  -type DFF DFF
add mapped point lif_inst/v[16]/q lif_inst/v_reg[16]/Q  -type DFF DFF
add mapped point lif_inst/v[17]/q lif_inst/v_reg[17]/Q  -type DFF DFF
add mapped point lif_inst/v[18]/q lif_inst/v_reg[18]/Q  -type DFF DFF
add mapped point lif_inst/v[19]/q lif_inst/v_reg[19]/Q  -type DFF DFF
add mapped point lif_inst/v[1]/q lif_inst/v_reg[1]/Q  -type DFF DFF
add mapped point lif_inst/v[2]/q lif_inst/v_reg[2]/Q  -type DFF DFF
add mapped point lif_inst/v[3]/q lif_inst/v_reg[3]/Q  -type DFF DFF
add mapped point lif_inst/v[4]/q lif_inst/v_reg[4]/Q  -type DFF DFF
add mapped point lif_inst/v[0]/q lif_inst/v_reg[0]/Q  -type DFF DFF
add mapped point lif_inst/v[6]/q lif_inst/v_reg[6]/Q  -type DFF DFF
add mapped point lif_inst/v[7]/q lif_inst/v_reg[7]/Q  -type DFF DFF
add mapped point lif_inst/v[8]/q lif_inst/v_reg[8]/Q  -type DFF DFF
add mapped point lif_inst/v[9]/q lif_inst/v_reg[9]/Q  -type DFF DFF
add mapped point lif_inst/v[5]/q lif_inst/v_reg[5]/Q  -type DFF DFF
add mapped point lif_inst/theta[0]/q lif_inst/theta_reg[0]/Q  -type DFF DFF
add mapped point lif_inst/theta[1]/q lif_inst/theta_reg[1]/Q  -type DFF DFF
add mapped point lif_inst/theta[2]/q lif_inst/theta_reg[2]/Q  -type DFF DFF
add mapped point lif_inst/theta[3]/q lif_inst/theta_reg[3]/Q  -type DFF DFF
add mapped point lif_inst/theta[4]/q lif_inst/theta_reg[4]/Q  -type DFF DFF
add mapped point lif_inst/theta[6]/q lif_inst/theta_reg[6]/Q  -type DFF DFF
add mapped point lif_inst/theta[7]/q lif_inst/theta_reg[7]/Q  -type DFF DFF
add mapped point lif_inst/theta[9]/q lif_inst/theta_reg[9]/Q  -type DFF DFF
add mapped point lif_inst/theta[5]/q lif_inst/theta_reg[5]/Q  -type DFF DFF
add mapped point lif_inst/theta[12]/q lif_inst/theta_reg[12]/Q  -type DFF DFF
add mapped point lif_inst/theta[13]/q lif_inst/theta_reg[13]/Q  -type DFF DFF
add mapped point lif_inst/theta[14]/q lif_inst/theta_reg[14]/Q  -type DFF DFF
add mapped point lif_inst/theta[11]/q lif_inst/theta_reg[11]/Q  -type DFF DFF
add mapped point lif_inst/theta[15]/q lif_inst/theta_reg[15]/Q  -type DFF DFF
add mapped point lif_inst/theta[8]/q lif_inst/theta_reg[8]/Q  -type DFF DFF
add mapped point lif_inst/theta[10]/q lif_inst/theta_reg[10]/Q  -type DFF DFF
add mapped point pm_inst/pace_pulse/q pm_inst/pace_pulse_reg/Q  -type DFF DFF
add mapped point pm_inst/blank_until[0]/q pm_inst/blank_until_reg[0]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[0]/q pm_inst/blank_until_reg[0]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[1]/q pm_inst/blank_until_reg[1]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[1]/q pm_inst/blank_until_reg[1]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[2]/q pm_inst/blank_until_reg[2]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[2]/q pm_inst/blank_until_reg[2]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[3]/q pm_inst/blank_until_reg[3]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[3]/q pm_inst/blank_until_reg[3]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[4]/q pm_inst/blank_until_reg[4]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[4]/q pm_inst/blank_until_reg[4]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[5]/q pm_inst/blank_until_reg[5]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[5]/q pm_inst/blank_until_reg[5]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[6]/q pm_inst/blank_until_reg[6]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[6]/q pm_inst/blank_until_reg[6]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[7]/q pm_inst/blank_until_reg[7]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[7]/q pm_inst/blank_until_reg[7]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[8]/q pm_inst/blank_until_reg[8]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[8]/q pm_inst/blank_until_reg[8]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[9]/q pm_inst/blank_until_reg[9]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[9]/q pm_inst/blank_until_reg[9]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[10]/q pm_inst/blank_until_reg[10]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[10]/q pm_inst/blank_until_reg[10]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[11]/q pm_inst/blank_until_reg[11]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[11]/q pm_inst/blank_until_reg[11]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[12]/q pm_inst/blank_until_reg[12]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[12]/q pm_inst/blank_until_reg[12]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[13]/q pm_inst/blank_until_reg[13]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[13]/q pm_inst/blank_until_reg[13]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[14]/q pm_inst/blank_until_reg[14]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[14]/q pm_inst/blank_until_reg[14]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[15]/q pm_inst/blank_until_reg[15]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[15]/q pm_inst/blank_until_reg[15]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[16]/q pm_inst/blank_until_reg[16]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[16]/q pm_inst/blank_until_reg[16]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[17]/q pm_inst/blank_until_reg[17]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[17]/q pm_inst/blank_until_reg[17]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[18]/q pm_inst/blank_until_reg[18]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[18]/q pm_inst/blank_until_reg[18]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[19]/q pm_inst/blank_until_reg[19]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[19]/q pm_inst/blank_until_reg[19]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[20]/q pm_inst/blank_until_reg[20]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[20]/q pm_inst/blank_until_reg[20]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[21]/q pm_inst/blank_until_reg[21]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[21]/q pm_inst/blank_until_reg[21]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[22]/q pm_inst/blank_until_reg[22]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[22]/q pm_inst/blank_until_reg[22]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[23]/q pm_inst/blank_until_reg[23]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[23]/q pm_inst/blank_until_reg[23]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[24]/q pm_inst/blank_until_reg[24]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[24]/q pm_inst/blank_until_reg[24]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[25]/q pm_inst/blank_until_reg[25]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[25]/q pm_inst/blank_until_reg[25]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[26]/q pm_inst/blank_until_reg[26]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[26]/q pm_inst/blank_until_reg[26]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[27]/q pm_inst/blank_until_reg[27]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[27]/q pm_inst/blank_until_reg[27]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[28]/q pm_inst/blank_until_reg[28]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[28]/q pm_inst/blank_until_reg[28]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[29]/q pm_inst/blank_until_reg[29]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[29]/q pm_inst/blank_until_reg[29]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[30]/q pm_inst/blank_until_reg[30]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[30]/q pm_inst/blank_until_reg[30]/QN  -type DFF DFF
add mapped point pm_inst/blank_until[31]/q pm_inst/blank_until_reg[31]/Q  -type DFF DFF
add mapped point pm_inst/blank_until[31]/q pm_inst/blank_until_reg[31]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[0]/q pm_inst/refract_until_reg[0]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[0]/q pm_inst/refract_until_reg[0]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[1]/q pm_inst/refract_until_reg[1]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[1]/q pm_inst/refract_until_reg[1]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[2]/q pm_inst/refract_until_reg[2]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[2]/q pm_inst/refract_until_reg[2]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[3]/q pm_inst/refract_until_reg[3]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[3]/q pm_inst/refract_until_reg[3]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[4]/q pm_inst/refract_until_reg[4]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[4]/q pm_inst/refract_until_reg[4]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[5]/q pm_inst/refract_until_reg[5]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[5]/q pm_inst/refract_until_reg[5]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[6]/q pm_inst/refract_until_reg[6]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[6]/q pm_inst/refract_until_reg[6]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[7]/q pm_inst/refract_until_reg[7]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[7]/q pm_inst/refract_until_reg[7]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[8]/q pm_inst/refract_until_reg[8]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[8]/q pm_inst/refract_until_reg[8]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[9]/q pm_inst/refract_until_reg[9]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[9]/q pm_inst/refract_until_reg[9]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[10]/q pm_inst/refract_until_reg[10]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[10]/q pm_inst/refract_until_reg[10]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[11]/q pm_inst/refract_until_reg[11]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[11]/q pm_inst/refract_until_reg[11]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[12]/q pm_inst/refract_until_reg[12]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[12]/q pm_inst/refract_until_reg[12]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[13]/q pm_inst/refract_until_reg[13]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[13]/q pm_inst/refract_until_reg[13]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[14]/q pm_inst/refract_until_reg[14]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[14]/q pm_inst/refract_until_reg[14]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[15]/q pm_inst/refract_until_reg[15]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[15]/q pm_inst/refract_until_reg[15]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[16]/q pm_inst/refract_until_reg[16]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[16]/q pm_inst/refract_until_reg[16]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[17]/q pm_inst/refract_until_reg[17]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[17]/q pm_inst/refract_until_reg[17]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[18]/q pm_inst/refract_until_reg[18]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[18]/q pm_inst/refract_until_reg[18]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[19]/q pm_inst/refract_until_reg[19]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[19]/q pm_inst/refract_until_reg[19]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[20]/q pm_inst/refract_until_reg[20]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[20]/q pm_inst/refract_until_reg[20]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[21]/q pm_inst/refract_until_reg[21]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[21]/q pm_inst/refract_until_reg[21]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[22]/q pm_inst/refract_until_reg[22]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[22]/q pm_inst/refract_until_reg[22]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[23]/q pm_inst/refract_until_reg[23]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[23]/q pm_inst/refract_until_reg[23]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[24]/q pm_inst/refract_until_reg[24]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[24]/q pm_inst/refract_until_reg[24]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[25]/q pm_inst/refract_until_reg[25]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[25]/q pm_inst/refract_until_reg[25]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[26]/q pm_inst/refract_until_reg[26]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[26]/q pm_inst/refract_until_reg[26]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[27]/q pm_inst/refract_until_reg[27]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[27]/q pm_inst/refract_until_reg[27]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[28]/q pm_inst/refract_until_reg[28]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[28]/q pm_inst/refract_until_reg[28]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[29]/q pm_inst/refract_until_reg[29]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[29]/q pm_inst/refract_until_reg[29]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[30]/q pm_inst/refract_until_reg[30]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[30]/q pm_inst/refract_until_reg[30]/QN  -type DFF DFF
add mapped point pm_inst/refract_until[31]/q pm_inst/refract_until_reg[31]/Q  -type DFF DFF
add mapped point pm_inst/refract_until[31]/q pm_inst/refract_until_reg[31]/QN  -type DFF DFF
add mapped point pm_inst/tick[0]/q pm_inst/tick_reg[0]/Q  -type DFF DFF
add mapped point pm_inst/tick[0]/q pm_inst/tick_reg[0]/QN  -type DFF DFF
add mapped point pm_inst/tick[1]/q pm_inst/tick_reg[1]/Q  -type DFF DFF
add mapped point pm_inst/tick[1]/q pm_inst/tick_reg[1]/QN  -type DFF DFF
add mapped point pm_inst/tick[2]/q pm_inst/tick_reg[2]/Q  -type DFF DFF
add mapped point pm_inst/tick[2]/q pm_inst/tick_reg[2]/QN  -type DFF DFF
add mapped point pm_inst/tick[3]/q pm_inst/tick_reg[3]/Q  -type DFF DFF
add mapped point pm_inst/tick[3]/q pm_inst/tick_reg[3]/QN  -type DFF DFF
add mapped point pm_inst/tick[4]/q pm_inst/tick_reg[4]/Q  -type DFF DFF
add mapped point pm_inst/tick[4]/q pm_inst/tick_reg[4]/QN  -type DFF DFF
add mapped point pm_inst/tick[5]/q pm_inst/tick_reg[5]/Q  -type DFF DFF
add mapped point pm_inst/tick[5]/q pm_inst/tick_reg[5]/QN  -type DFF DFF
add mapped point pm_inst/tick[6]/q pm_inst/tick_reg[6]/Q  -type DFF DFF
add mapped point pm_inst/tick[6]/q pm_inst/tick_reg[6]/QN  -type DFF DFF
add mapped point pm_inst/tick[7]/q pm_inst/tick_reg[7]/Q  -type DFF DFF
add mapped point pm_inst/tick[7]/q pm_inst/tick_reg[7]/QN  -type DFF DFF
add mapped point pm_inst/tick[8]/q pm_inst/tick_reg[8]/Q  -type DFF DFF
add mapped point pm_inst/tick[8]/q pm_inst/tick_reg[8]/QN  -type DFF DFF
add mapped point pm_inst/tick[9]/q pm_inst/tick_reg[9]/Q  -type DFF DFF
add mapped point pm_inst/tick[9]/q pm_inst/tick_reg[9]/QN  -type DFF DFF
add mapped point pm_inst/tick[10]/q pm_inst/tick_reg[10]/Q  -type DFF DFF
add mapped point pm_inst/tick[10]/q pm_inst/tick_reg[10]/QN  -type DFF DFF
add mapped point pm_inst/tick[11]/q pm_inst/tick_reg[11]/Q  -type DFF DFF
add mapped point pm_inst/tick[11]/q pm_inst/tick_reg[11]/QN  -type DFF DFF
add mapped point pm_inst/tick[12]/q pm_inst/tick_reg[12]/Q  -type DFF DFF
add mapped point pm_inst/tick[12]/q pm_inst/tick_reg[12]/QN  -type DFF DFF
add mapped point pm_inst/tick[13]/q pm_inst/tick_reg[13]/Q  -type DFF DFF
add mapped point pm_inst/tick[13]/q pm_inst/tick_reg[13]/QN  -type DFF DFF
add mapped point pm_inst/tick[14]/q pm_inst/tick_reg[14]/Q  -type DFF DFF
add mapped point pm_inst/tick[14]/q pm_inst/tick_reg[14]/QN  -type DFF DFF
add mapped point pm_inst/tick[15]/q pm_inst/tick_reg[15]/Q  -type DFF DFF
add mapped point pm_inst/tick[15]/q pm_inst/tick_reg[15]/QN  -type DFF DFF
add mapped point pm_inst/tick[16]/q pm_inst/tick_reg[16]/Q  -type DFF DFF
add mapped point pm_inst/tick[16]/q pm_inst/tick_reg[16]/QN  -type DFF DFF
add mapped point pm_inst/tick[17]/q pm_inst/tick_reg[17]/Q  -type DFF DFF
add mapped point pm_inst/tick[17]/q pm_inst/tick_reg[17]/QN  -type DFF DFF
add mapped point pm_inst/tick[18]/q pm_inst/tick_reg[18]/Q  -type DFF DFF
add mapped point pm_inst/tick[18]/q pm_inst/tick_reg[18]/QN  -type DFF DFF
add mapped point pm_inst/tick[19]/q pm_inst/tick_reg[19]/Q  -type DFF DFF
add mapped point pm_inst/tick[19]/q pm_inst/tick_reg[19]/QN  -type DFF DFF
add mapped point pm_inst/tick[20]/q pm_inst/tick_reg[20]/Q  -type DFF DFF
add mapped point pm_inst/tick[20]/q pm_inst/tick_reg[20]/QN  -type DFF DFF
add mapped point pm_inst/tick[21]/q pm_inst/tick_reg[21]/Q  -type DFF DFF
add mapped point pm_inst/tick[21]/q pm_inst/tick_reg[21]/QN  -type DFF DFF
add mapped point pm_inst/tick[22]/q pm_inst/tick_reg[22]/Q  -type DFF DFF
add mapped point pm_inst/tick[22]/q pm_inst/tick_reg[22]/QN  -type DFF DFF
add mapped point pm_inst/tick[23]/q pm_inst/tick_reg[23]/Q  -type DFF DFF
add mapped point pm_inst/tick[23]/q pm_inst/tick_reg[23]/QN  -type DFF DFF
add mapped point pm_inst/tick[24]/q pm_inst/tick_reg[24]/Q  -type DFF DFF
add mapped point pm_inst/tick[24]/q pm_inst/tick_reg[24]/QN  -type DFF DFF
add mapped point pm_inst/tick[25]/q pm_inst/tick_reg[25]/Q  -type DFF DFF
add mapped point pm_inst/tick[25]/q pm_inst/tick_reg[25]/QN  -type DFF DFF
add mapped point pm_inst/tick[26]/q pm_inst/tick_reg[26]/Q  -type DFF DFF
add mapped point pm_inst/tick[26]/q pm_inst/tick_reg[26]/QN  -type DFF DFF
add mapped point pm_inst/tick[27]/q pm_inst/tick_reg[27]/Q  -type DFF DFF
add mapped point pm_inst/tick[27]/q pm_inst/tick_reg[27]/QN  -type DFF DFF
add mapped point pm_inst/tick[28]/q pm_inst/tick_reg[28]/Q  -type DFF DFF
add mapped point pm_inst/tick[28]/q pm_inst/tick_reg[28]/QN  -type DFF DFF
add mapped point pm_inst/tick[29]/q pm_inst/tick_reg[29]/Q  -type DFF DFF
add mapped point pm_inst/tick[29]/q pm_inst/tick_reg[29]/QN  -type DFF DFF
add mapped point pm_inst/tick[30]/q pm_inst/tick_reg[30]/Q  -type DFF DFF
add mapped point pm_inst/tick[30]/q pm_inst/tick_reg[30]/QN  -type DFF DFF
add mapped point pm_inst/tick[31]/q pm_inst/tick_reg[31]/Q  -type DFF DFF
add mapped point pm_inst/tick[31]/q pm_inst/tick_reg[31]/QN  -type DFF DFF
add mapped point pm_inst/timer_since_event[0]/q pm_inst/timer_since_event_reg[0]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[1]/q pm_inst/timer_since_event_reg[1]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[2]/q pm_inst/timer_since_event_reg[2]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[3]/q pm_inst/timer_since_event_reg[3]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[4]/q pm_inst/timer_since_event_reg[4]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[5]/q pm_inst/timer_since_event_reg[5]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[6]/q pm_inst/timer_since_event_reg[6]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[7]/q pm_inst/timer_since_event_reg[7]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[8]/q pm_inst/timer_since_event_reg[8]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[9]/q pm_inst/timer_since_event_reg[9]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[10]/q pm_inst/timer_since_event_reg[10]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[11]/q pm_inst/timer_since_event_reg[11]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[12]/q pm_inst/timer_since_event_reg[12]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[13]/q pm_inst/timer_since_event_reg[13]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[14]/q pm_inst/timer_since_event_reg[14]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[15]/q pm_inst/timer_since_event_reg[15]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[16]/q pm_inst/timer_since_event_reg[16]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[17]/q pm_inst/timer_since_event_reg[17]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[18]/q pm_inst/timer_since_event_reg[18]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[19]/q pm_inst/timer_since_event_reg[19]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[20]/q pm_inst/timer_since_event_reg[20]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[21]/q pm_inst/timer_since_event_reg[21]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[22]/q pm_inst/timer_since_event_reg[22]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[23]/q pm_inst/timer_since_event_reg[23]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[24]/q pm_inst/timer_since_event_reg[24]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[25]/q pm_inst/timer_since_event_reg[25]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[26]/q pm_inst/timer_since_event_reg[26]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[27]/q pm_inst/timer_since_event_reg[27]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[28]/q pm_inst/timer_since_event_reg[28]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[29]/q pm_inst/timer_since_event_reg[29]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[30]/q pm_inst/timer_since_event_reg[30]/Q  -type DFF DFF
add mapped point pm_inst/timer_since_event[31]/q pm_inst/timer_since_event_reg[31]/Q  -type DFF DFF
add mapped point rom_inst/data[0]/q rom_inst/data_reg[0]/Q  -type DFF DFF
add mapped point rom_inst/data[11]/q rom_inst/data_reg[11]/Q  -type DFF DFF
add mapped point sample_clk_en/q sample_clk_en_reg/Q  -type DFF DFF
add mapped point sample_clk_en/q sample_clk_en_reg/QN  -type DFF DFF
add mapped point divcnt[6]/q divcnt_reg[6]/Q  -type DFF DFF
add mapped point divcnt[5]/q divcnt_reg[5]/Q  -type DFF DFF
add mapped point divcnt[5]/q divcnt_reg[5]/QN  -type DFF DFF
add mapped point divcnt[4]/q divcnt_reg[4]/Q  -type DFF DFF
add mapped point divcnt[4]/q divcnt_reg[4]/QN  -type DFF DFF
add mapped point sample_addr[3]/q sample_addr_reg[3]/Q  -type DFF DFF
add mapped point sample_addr[3]/q sample_addr_reg[3]/QN  -type DFF DFF
add mapped point divcnt[3]/q divcnt_reg[3]/Q  -type DFF DFF
add mapped point divcnt[3]/q divcnt_reg[3]/QN  -type DFF DFF
add mapped point sample_addr[1]/q sample_addr_reg[1]/Q  -type DFF DFF
add mapped point sample_addr[1]/q sample_addr_reg[1]/QN  -type DFF DFF
add mapped point sample_addr[2]/q sample_addr_reg[2]/Q  -type DFF DFF
add mapped point sample_addr[2]/q sample_addr_reg[2]/QN  -type DFF DFF
add mapped point divcnt[2]/q divcnt_reg[2]/Q  -type DFF DFF
add mapped point divcnt[2]/q divcnt_reg[2]/QN  -type DFF DFF
add mapped point sample_addr[0]/q sample_addr_reg[0]/Q  -type DFF DFF
add mapped point sample_addr[0]/q sample_addr_reg[0]/QN  -type DFF DFF
add mapped point divcnt[1]/q divcnt_reg[1]/Q  -type DFF DFF
add mapped point divcnt[1]/q divcnt_reg[1]/QN  -type DFF DFF
add mapped point divcnt[0]/q divcnt_reg[0]/Q  -type DFF DFF
add mapped point divcnt[0]/q divcnt_reg[0]/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
